import type { Metadata } from "next";
import "./globals.scss";

import LayoutClient from "./layout-client";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <p id="accessibility"><a href="#container">본문바로가기</a></p>
                <LayoutClient>
                    {children}
                </LayoutClient>
            </body>
        </html>
    );
}
